name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Mongo URI
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: echo "$MONGO_URI"
      - name: Google Client ID
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        run: echo "$GOOGLE_CLIENT_ID"
      - name: Google Client Secret
        env:
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: echo "$GOOGLE_CLIENT_SECRET"
      -run: npm ci
        
